"""case table

Revision ID: 819241cd8b43
Revises: c01d6e512534
Create Date: 2023-12-20 15:49:09.497886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819241cd8b43'
down_revision = 'c01d6e512534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.Column('positioning', sa.String(length=120), nullable=False),
    sa.Column('mission', sa.String(length=120), nullable=False),
    sa.Column('emotions', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('case')
    # ### end Alembic commands ###
