"""service table

Revision ID: 87903c7524f8
Revises: 87f5daf68935
Create Date: 2023-12-20 16:20:53.378452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87903c7524f8'
down_revision = '87f5daf68935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('image', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('essence', sa.String(length=120), nullable=False),
    sa.Column('development_stages', sa.String(length=120), nullable=False),
    sa.Column('cost_description', sa.String(length=120), nullable=False),
    sa.Column('cost', sa.String(length=20), nullable=False),
    sa.Column('demand', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('service')
    # ### end Alembic commands ###
