"""discussion table

Revision ID: ae495b3cc000
Revises: 92dcbfa81e21
Create Date: 2023-12-20 19:33:54.477834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae495b3cc000'
down_revision = '92dcbfa81e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=60),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=120),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('essence',
               existing_type=sa.TEXT(length=120),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('development_stages',
               existing_type=sa.TEXT(length=120),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('cost_description',
               existing_type=sa.TEXT(length=120),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('cost',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('demand',
               existing_type=sa.TEXT(length=120),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('demand',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(length=120),
               existing_nullable=False)
        batch_op.alter_column('cost',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=False)
        batch_op.alter_column('cost_description',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(length=120),
               existing_nullable=False)
        batch_op.alter_column('development_stages',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(length=120),
               existing_nullable=False)
        batch_op.alter_column('essence',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(length=120),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(length=120),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(length=60),
               existing_nullable=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
